services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: vectorscaledb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5555:5432"
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
